image:
  file: .gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
  onOpen: open-preview
- port: 9001
  onOpen: ignore
- port: 15672
  onOpen: ignore
  visibility: public
- port: 8025
  onOpen: ignore
  visibility: private
  name: Mailpit
  description: Shows the Webinterface for Mailpit
- port: 1025
  onOpen: ignore
  visibility: private
  name: Mailpit Mailserver
  description: Endpoint for Mailpit
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
github:
  prebuilds:
    master: true
    branches: true
tasks:
  - init: > 
            sudo composer self-update &&
            cd $GITPOD_REPO_ROOT &&
            composer config -g -a http-basic.repo.magento.com ${MAGENTO_COMPOSER_AUTH_USER} ${MAGENTO_COMPOSER_AUTH_PASS} &&
            composer create-project --no-interaction --no-progress --repository-url=https://repo.magento.com/ magento/project-community-edition=${MAGENTO_VERSION} magento2 &&
            cd magento2 && cp -avr .* $GITPOD_REPO_ROOT;
            cd $GITPOD_REPO_ROOT && rm -r -f magento2 && git checkout -- .gitignore;
            npm install cypress --save-dev
    command: gp ports await 3306 &&
             cd $GITPOD_REPO_ROOT &&
             test ! -f $GITPOD_REPO_ROOT/gitpod/db-installed.flag && $GITPOD_REPO_ROOT/gitpod/m2-install.sh ;
             url=$(gp url | awk -F"//" {'print $2'}) && url="https://8002-"$url"/"  &&
             php bin/magento config:set web/unsecure/base_url $url  &&
             php bin/magento config:set web/unsecure/base_link_url $url  &&
             php bin/magento config:set web/secure/base_url $url
  - name: "Supervisor Services"
    command: cd $GITPOD_REPO_ROOT &&
             test ! -f $GITPOD_REPO_ROOT/gitpod/db-installed.flag && sudo mv /var/lib/mysql $GITPOD_REPO_ROOT/ ;
             sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/supervisor/conf.d/sp-php-fpm.conf &&
             sudo sed -i 's#$PHP_VERSION#'$PHP_VERSION'#g' /etc/supervisor/conf.d/sp-php-fpm.conf &&
             sudo cp $GITPOD_REPO_ROOT/gitpod/sp-redis.conf /etc/supervisor/conf.d/redis.conf &&
             sudo cp $GITPOD_REPO_ROOT/gitpod/sp-elasticsearch.conf /etc/supervisor/conf.d/elasticsearch.conf &&
             sudo sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf &&
             sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/mysql/conf.d/mysqld.cnf &&
             sudo sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/supervisor/conf.d/mysql.conf &&
             sudo /etc/init.d/supervisor start
  - name: "Nginx"
    command: gp ports await 3306 &&
             sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/nginx/nginx.conf &&
             service nginx start
